[workspace]
release_always = false
changelog_update = true
git_release_enable = true
git_tag_enable = true
git_tag_name = "release/{version}"
semver_check = true
pr_branch_prefix = "release/prepare/"
pr_labels = ["release"]
pr_draft = false
repo_url = "https://github.com/eklipse2k8/oas3-gen"
release_commits = "^feat:"

[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

"""

body = """
{% if version -%}
## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
## [Unreleased]
{% endif -%}

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
{%- if commit.scope -%}
- **{{ commit.scope }}:** {{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/eklipse2k8/oas3-gen/commit/{{ commit.id }}))
{% else -%}
- {{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/eklipse2k8/oas3-gen/commit/{{ commit.id }}))
{% endif -%}
{% endfor %}
{% endfor %}
"""

trim = true
protect_breaking_commits = true

commit_parsers = [
  { message = "^feat", group = "Added" },
  { message = "^fix", group = "Fixed" },
  { message = "^doc", group = "Documentation" },
  { message = "^perf", group = "Performance" },
  { message = "^refactor", group = "Changed" },
  { message = "^style", group = "Styling" },
  { message = "^test", group = "Testing" },
  { message = "^build", group = "Build" },
  { message = "^ci", group = "CI/CD" },
  { message = "^chore\\(release\\)", skip = true },
  { message = "^chore\\(deps\\)", skip = true },
  { message = "^chore", group = "Miscellaneous" },
  { body = ".*security", group = "Security" },
]

[[package]]
name = "oas3-gen"
changelog_path = "./CHANGELOG.md"
changelog_include = ["oas3-gen-support"]
changelog_update = true 
publish_all_features = true

[[package]]
name = "oas3-gen-support"
changelog_update = false
git_release_enable = false
publish = true
